// File generated by Antigravity
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyDGQBkrNf-Xzro0mQ1yMHBFfgmDMEnIHt0",
  authDomain: "smartinvoice-ea321.firebaseapp.com",
  projectId: "smartinvoice-ea321",
  storageBucket: "smartinvoice-ea321.firebasestorage.app",
  messagingSenderId: "606100022692",
  appId: "1:606100022692:web:b8d8f4a39abcdc660c0d31",
  measurementId: "G-Y8ND13SFJ1",
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfkQMRCbVuNR3l-Jl2IitCcFZy9r2eBU',
    appId: '1:606100022692:android:07b988eaf1f210790c0d31',
    messagingSenderId: '606100022692',
    projectId: 'smartinvoice-ea321',
    storageBucket: 'smartinvoice-ea321.firebasestorage.app',
  );
}
